spring.application.name=demo
server.port=8090

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/projectskateboard
spring.datasource.username=root
spring.datasource.password=trongvinh_2k6
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

#config jwt
project.jwt.base64-secret=aGt+l495xiSEUkVSDYyuaQDPm8Emb//pk7+SUpUaAjM=

#1000 day
project.jwt.access-token-validity-in-seconds=86400000

project.jwt.refresh-token-validity-in-seconds=86400000

# default page size
spring.data.web.pageable.default-page-size=6

# max page size 
spring.data.web.pageable.max-page-size=100

#false: start with 0; true: start with 1
spring.data.web.pageable.one-indexed-parameters=true
